#!/usr/bin/env python
"""Generate the private-name map for the dual GLDirect/Mesa dispatcher.

The OpenGL 1.1 ABI functions must remain normal exports, but the direct D3D9
implementations and the Mesa forwarding implementations must coexist in the
same DLL. This generator gives the former a ``direct_`` prefix without
hand-maintaining several hundred preprocessor definitions.
"""

from __future__ import print_function

import io
import os
import re


HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SOURCE = os.path.join(ROOT, "src", "gl_legacy_stubs.c")
OUTPUT = os.path.join(ROOT, "src", "gl_legacy_rename.h")

DEFINITION = re.compile(
    r"\b(?:void|GLboolean|GLenum|GLuint|GLint|const\s+GLubyte\s*\*)"
    r"\s+APIENTRY\s+(gl\w+)\s*\("
)


def main():
    with io.open(SOURCE, encoding="utf-8", errors="replace") as stream:
        names = sorted(set(DEFINITION.findall(stream.read())))

    if not names:
        raise SystemExit("no legacy OpenGL entry points found in %s" % SOURCE)

    lines = [
        "/* Generated by tools/gen_legacy_rename.py. Do not edit manually. */",
        "#ifndef GLD_LEGACY_RENAME_H",
        "#define GLD_LEGACY_RENAME_H",
        "",
    ]
    lines.extend("#define %s direct_%s" % (name, name) for name in names)
    lines.extend(["", "#endif /* GLD_LEGACY_RENAME_H */", ""])

    with io.open(OUTPUT, "w", encoding="ascii", newline="\n") as stream:
        stream.write("\n".join(lines))

    print("generated %s with %d entry points" % (OUTPUT, len(names)))


if __name__ == "__main__":
    main()
