"""Per-command classification for the 487 unresolved GL core names.

Generator input for tools/gen_gl_stubs.py.  glmap.json supplies the exact
signature of every name; this file supplies the domain judgement glmap.json
cannot: which D3D9-facing behaviour, if any, each name can be given.

  "glName": ("<family>", "<forward>" | None)

The second element is normally the name of the existing _gls* function the
generated stub forwards to; gen_gl_stubs.py derives the argument mapping from
the family template plus glmap.json's params[].  Three families cannot have
their argument mapping derived from the name - the base entry point takes a
different shape per command - so for those the second element is the C text
itself, using the parameter names from glmap.json:

  direct-forward   a C expression (its value is what the stub returns)
  indexed-state    a C block, opening with the index != 0 early-out
  multi-bind       a C block containing the per-element loop

Families and the template gen_gl_stubs.py applies to each:

  alias              (not listed here - the 335 missing_alias names are resolved
                     through glmap.json's alias_to_core and point straight at
                     whatever PROC their core spelling already resolved to)
  dsa                bind-call-restore around an existing non-DSA _gls* entry
                     point; the per-name bind target and forward call live in
                     tools/gl_dsa_mapping.py, which needs an extra field the
                     other families do not
  fp64-demote        cast every GLdouble to GLfloat, call the f-suffixed sibling
  packed-type        unpack GL_[UNSIGNED_]INT_2_10_10_10_REV into four floats,
                     call the float entry point
  attrib-type-variant convert to float (applying the N-suffix integer
                     normalisation rule), call _glsVertexAttrib4f
  gl14-variant       convert to float, call _glsSecondaryColor3f/_glsWindowPos3f
  integer-variant    call the non-I sibling
  uniform-widen      GLuint -> GLint, or pack a non-square matrix one column per
                     float4 constant register and upload through _glsUniform4fv
  program-uniform    glUseProgram(program), call the existing _glsUniform*,
                     restore the previously bound program
  multi-bind         loop, calling the existing single-object bind per element
  indexed-state      index 0 forwards to the base entry point, index > 0 is a
                     documented no-op (D3D9 has one viewport/scissor/blend state)
  robustness         validate bufSize, call the unbounded sibling
  get-gap            read state the wrapper already tracks into the out params
  is-misc            small hand-written body over existing object tables
  tf-bookkeeping     transform-feedback object state implemented by
                     advanced_emulation.c
  direct-forward     a one-off forward to a near-equivalent existing entry point
  noop-legal         doing nothing is what the spec permits (hints, debug
                     labels, invalidation) - correctly typed, silent
  ceiling-noop       historical classification retained for registry grouping;
                     completed names are routed to advanced_emulation.c by the
                     generator's ADVANCED_EMULATION set

The point of every entry, including ceiling-noop, is that the name resolves to a
stub with the *exact* signature from glmap.json.  Before this table existed,
gldGetProcAddress_GL46 guessed the argument count from the name and handed back
a no-op with the wrong __stdcall stack adjustment, which corrupts the stack on
x86.  A ceiling-noop is a real fix for that even when it does no drawing.
"""

CLASSIFICATION = {
    # ----- dsa (101) -----
    "glBindTextureUnit":                          ("dsa", None),
    "glBlitNamedFramebuffer":                     ("dsa", None),
    "glCheckNamedFramebufferStatus":              ("dsa", None),
    "glClearNamedBufferData":                     ("dsa", None),
    "glClearNamedBufferSubData":                  ("dsa", None),
    "glClearNamedFramebufferfi":                  ("dsa", None),
    "glClearNamedFramebufferfv":                  ("dsa", None),
    "glClearNamedFramebufferiv":                  ("dsa", None),
    "glClearNamedFramebufferuiv":                 ("dsa", None),
    "glCompressedTextureSubImage1D":              ("dsa", None),
    "glCompressedTextureSubImage2D":              ("dsa", None),
    "glCompressedTextureSubImage3D":              ("dsa", None),
    "glCopyTextureSubImage1D":                    ("dsa", None),
    "glCopyTextureSubImage2D":                    ("dsa", None),
    "glCopyTextureSubImage3D":                    ("dsa", None),
    "glCopyNamedBufferSubData":                   ("dsa", None),
    "glCreateBuffers":                            ("dsa", None),
    "glCreateFramebuffers":                       ("dsa", None),
    "glCreateProgramPipelines":                   ("dsa", None),
    "glCreateQueries":                            ("dsa", None),
    "glCreateRenderbuffers":                      ("dsa", None),
    "glCreateSamplers":                           ("dsa", None),
    "glCreateTextures":                           ("dsa", None),
    "glCreateTransformFeedbacks":                 ("dsa", None),
    "glCreateVertexArrays":                       ("dsa", None),
    "glDisableVertexArrayAttrib":                 ("dsa", None),
    "glEnableVertexArrayAttrib":                  ("dsa", None),
    "glFlushMappedNamedBufferRange":              ("dsa", None),
    "glGenerateTextureMipmap":                    ("dsa", None),
    "glGetCompressedTextureImage":                ("dsa", None),
    "glGetCompressedTextureSubImage":             ("dsa", None),
    "glGetNamedBufferParameteri64v":              ("dsa", None),
    "glGetNamedBufferParameteriv":                ("dsa", None),
    "glGetNamedBufferPointerv":                   ("dsa", None),
    "glGetNamedBufferSubData":                    ("dsa", None),
    "glGetNamedFramebufferAttachmentParameteriv": ("dsa", None),
    "glGetNamedFramebufferParameteriv":           ("dsa", None),
    "glGetNamedRenderbufferParameteriv":          ("dsa", None),
    "glGetQueryBufferObjecti64v":                 ("dsa", None),
    "glGetQueryBufferObjectiv":                   ("dsa", None),
    "glGetQueryBufferObjectui64v":                ("dsa", None),
    "glGetQueryBufferObjectuiv":                  ("dsa", None),
    "glGetTextureImage":                          ("dsa", None),
    "glGetTextureLevelParameterfv":               ("dsa", None),
    "glGetTextureLevelParameteriv":               ("dsa", None),
    "glGetTextureParameterIiv":                   ("dsa", None),
    "glGetTextureParameterIuiv":                  ("dsa", None),
    "glGetTextureParameterfv":                    ("dsa", None),
    "glGetTextureParameteriv":                    ("dsa", None),
    "glGetTextureSubImage":                       ("dsa", None),
    "glGetTransformFeedbackVarying":              ("dsa", None),
    "glGetTransformFeedbacki64_v":                ("dsa", None),
    "glGetTransformFeedbacki_v":                  ("dsa", None),
    "glGetTransformFeedbackiv":                   ("dsa", None),
    "glGetVertexArrayIndexed64iv":                ("dsa", None),
    "glGetVertexArrayIndexediv":                  ("dsa", None),
    "glGetVertexArrayiv":                         ("dsa", None),
    "glInvalidateNamedFramebufferData":           ("dsa", None),
    "glInvalidateNamedFramebufferSubData":        ("dsa", None),
    "glMapNamedBuffer":                           ("dsa", None),
    "glMapNamedBufferRange":                      ("dsa", None),
    "glNamedBufferData":                          ("dsa", None),
    "glNamedBufferStorage":                       ("dsa", None),
    "glNamedBufferSubData":                       ("dsa", None),
    "glNamedFramebufferDrawBuffer":               ("dsa", None),
    "glNamedFramebufferDrawBuffers":              ("dsa", None),
    "glNamedFramebufferParameteri":               ("dsa", None),
    "glNamedFramebufferReadBuffer":               ("dsa", None),
    "glNamedFramebufferRenderbuffer":             ("dsa", None),
    "glNamedFramebufferTexture":                  ("dsa", None),
    "glNamedFramebufferTextureLayer":             ("dsa", None),
    "glNamedRenderbufferStorage":                 ("dsa", None),
    "glNamedRenderbufferStorageMultisample":      ("dsa", None),
    "glTextureBuffer":                            ("dsa", None),
    "glTextureBufferRange":                       ("dsa", None),
    "glTextureParameterIiv":                      ("dsa", None),
    "glTextureParameterIuiv":                     ("dsa", None),
    "glTextureParameterf":                        ("dsa", None),
    "glTextureParameterfv":                       ("dsa", None),
    "glTextureParameteri":                        ("dsa", None),
    "glTextureParameteriv":                       ("dsa", None),
    "glTextureStorage1D":                         ("dsa", None),
    "glTextureStorage2D":                         ("dsa", None),
    "glTextureStorage2DMultisample":              ("dsa", None),
    "glTextureStorage3D":                         ("dsa", None),
    "glTextureStorage3DMultisample":              ("dsa", None),
    "glTextureSubImage1D":                        ("dsa", None),
    "glTextureSubImage2D":                        ("dsa", None),
    "glTextureSubImage3D":                        ("dsa", None),
    "glTextureView":                              ("dsa", None),
    "glTransformFeedbackBufferBase":              ("dsa", None),
    "glTransformFeedbackBufferRange":             ("dsa", None),
    "glUnmapNamedBuffer":                         ("dsa", None),
    "glVertexArrayAttribBinding":                 ("dsa", None),
    "glVertexArrayAttribFormat":                  ("dsa", None),
    "glVertexArrayAttribIFormat":                 ("dsa", None),
    "glVertexArrayAttribLFormat":                 ("dsa", None),
    "glVertexArrayBindingDivisor":                ("dsa", None),
    "glVertexArrayElementBuffer":                 ("dsa", None),
    "glVertexArrayVertexBuffer":                  ("dsa", None),
    "glVertexArrayVertexBuffers":                 ("dsa", None),
    # ----- program-uniform (50) -----
    "glProgramUniform1d":          ("program-uniform", "_glsUniform1f"),
    "glProgramUniform1dv":         ("program-uniform", "_glsUniform1fv"),
    "glProgramUniform1f":          ("program-uniform", "_glsUniform1f"),
    "glProgramUniform1fv":         ("program-uniform", "_glsUniform1fv"),
    "glProgramUniform1i":          ("program-uniform", "_glsUniform1i"),
    "glProgramUniform1iv":         ("program-uniform", "_glsUniform1iv"),
    "glProgramUniform1ui":         ("program-uniform", "_glsUniform1i"),
    "glProgramUniform1uiv":        ("program-uniform", "_glsUniform1iv"),
    "glProgramUniform2d":          ("program-uniform", "_glsUniform2f"),
    "glProgramUniform2dv":         ("program-uniform", "_glsUniform2fv"),
    "glProgramUniform2f":          ("program-uniform", "_glsUniform2f"),
    "glProgramUniform2fv":         ("program-uniform", "_glsUniform2fv"),
    "glProgramUniform2i":          ("program-uniform", "_glsUniform2i"),
    "glProgramUniform2iv":         ("program-uniform", "_glsUniform2iv"),
    "glProgramUniform2ui":         ("program-uniform", "_glsUniform2i"),
    "glProgramUniform2uiv":        ("program-uniform", "_glsUniform2iv"),
    "glProgramUniform3d":          ("program-uniform", "_glsUniform3f"),
    "glProgramUniform3dv":         ("program-uniform", "_glsUniform3fv"),
    "glProgramUniform3f":          ("program-uniform", "_glsUniform3f"),
    "glProgramUniform3fv":         ("program-uniform", "_glsUniform3fv"),
    "glProgramUniform3i":          ("program-uniform", "_glsUniform3i"),
    "glProgramUniform3iv":         ("program-uniform", "_glsUniform3iv"),
    "glProgramUniform3ui":         ("program-uniform", "_glsUniform3i"),
    "glProgramUniform3uiv":        ("program-uniform", "_glsUniform3iv"),
    "glProgramUniform4d":          ("program-uniform", "_glsUniform4f"),
    "glProgramUniform4dv":         ("program-uniform", "_glsUniform4fv"),
    "glProgramUniform4f":          ("program-uniform", "_glsUniform4f"),
    "glProgramUniform4fv":         ("program-uniform", "_glsUniform4fv"),
    "glProgramUniform4i":          ("program-uniform", "_glsUniform4i"),
    "glProgramUniform4iv":         ("program-uniform", "_glsUniform4iv"),
    "glProgramUniform4ui":         ("program-uniform", "_glsUniform4i"),
    "glProgramUniform4uiv":        ("program-uniform", "_glsUniform4iv"),
    "glProgramUniformMatrix2dv":   ("program-uniform", "_glsUniformMatrix2fv"),
    "glProgramUniformMatrix2fv":   ("program-uniform", "_glsUniformMatrix2fv"),
    "glProgramUniformMatrix2x3dv": ("program-uniform", "_glsUniform4fv"),
    "glProgramUniformMatrix2x3fv": ("program-uniform", "_glsUniform4fv"),
    "glProgramUniformMatrix2x4dv": ("program-uniform", "_glsUniform4fv"),
    "glProgramUniformMatrix2x4fv": ("program-uniform", "_glsUniform4fv"),
    "glProgramUniformMatrix3dv":   ("program-uniform", "_glsUniformMatrix3fv"),
    "glProgramUniformMatrix3fv":   ("program-uniform", "_glsUniformMatrix3fv"),
    "glProgramUniformMatrix3x2dv": ("program-uniform", "_glsUniform4fv"),
    "glProgramUniformMatrix3x2fv": ("program-uniform", "_glsUniform4fv"),
    "glProgramUniformMatrix3x4dv": ("program-uniform", "_glsUniform4fv"),
    "glProgramUniformMatrix3x4fv": ("program-uniform", "_glsUniform4fv"),
    "glProgramUniformMatrix4dv":   ("program-uniform", "_glsUniformMatrix4fv"),
    "glProgramUniformMatrix4fv":   ("program-uniform", "_glsUniformMatrix4fv"),
    "glProgramUniformMatrix4x2dv": ("program-uniform", "_glsUniform4fv"),
    "glProgramUniformMatrix4x2fv": ("program-uniform", "_glsUniform4fv"),
    "glProgramUniformMatrix4x3dv": ("program-uniform", "_glsUniform4fv"),
    "glProgramUniformMatrix4x3fv": ("program-uniform", "_glsUniform4fv"),
    # ----- attrib-type-variant (40) -----
    "glVertexAttrib1d":    ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttrib1dv":   ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttrib1fv":   ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttrib1s":    ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttrib1sv":   ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttrib2d":    ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttrib2dv":   ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttrib2fv":   ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttrib2s":    ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttrib2sv":   ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttrib3d":    ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttrib3dv":   ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttrib3fv":   ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttrib3s":    ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttrib3sv":   ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttrib4Nbv":  ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttrib4Niv":  ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttrib4Nsv":  ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttrib4Nub":  ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttrib4Nubv": ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttrib4Nuiv": ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttrib4Nusv": ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttrib4bv":   ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttrib4d":    ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttrib4dv":   ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttrib4fv":   ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttrib4iv":   ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttrib4s":    ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttrib4sv":   ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttrib4ubv":  ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttrib4uiv":  ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttrib4usv":  ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttribL1d":   ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttribL1dv":  ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttribL2d":   ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttribL2dv":  ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttribL3d":   ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttribL3dv":  ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttribL4d":   ("attrib-type-variant", "_glsVertexAttrib4f"),
    "glVertexAttribL4dv":  ("attrib-type-variant", "_glsVertexAttrib4f"),
    # ----- packed-type (38) -----
    "glColorP3ui":           ("packed-type", "_glsColor4f"),
    "glColorP3uiv":          ("packed-type", "_glsColor4f"),
    "glColorP4ui":           ("packed-type", "_glsColor4f"),
    "glColorP4uiv":          ("packed-type", "_glsColor4f"),
    "glMultiTexCoordP1ui":   ("packed-type", "_glsMultiTexCoord4fARB"),
    "glMultiTexCoordP1uiv":  ("packed-type", "_glsMultiTexCoord4fARB"),
    "glMultiTexCoordP2ui":   ("packed-type", "_glsMultiTexCoord4fARB"),
    "glMultiTexCoordP2uiv":  ("packed-type", "_glsMultiTexCoord4fARB"),
    "glMultiTexCoordP3ui":   ("packed-type", "_glsMultiTexCoord4fARB"),
    "glMultiTexCoordP3uiv":  ("packed-type", "_glsMultiTexCoord4fARB"),
    "glMultiTexCoordP4ui":   ("packed-type", "_glsMultiTexCoord4fARB"),
    "glMultiTexCoordP4uiv":  ("packed-type", "_glsMultiTexCoord4fARB"),
    "glNormalP3ui":          ("packed-type", "_glsNormal3f"),
    "glNormalP3uiv":         ("packed-type", "_glsNormal3f"),
    "glSecondaryColorP3ui":  ("packed-type", "_glsSecondaryColor3f"),
    "glSecondaryColorP3uiv": ("packed-type", "_glsSecondaryColor3f"),
    "glTexCoordP1ui":        ("packed-type", "_glsTexCoord4f"),
    "glTexCoordP1uiv":       ("packed-type", "_glsTexCoord4f"),
    "glTexCoordP2ui":        ("packed-type", "_glsTexCoord4f"),
    "glTexCoordP2uiv":       ("packed-type", "_glsTexCoord4f"),
    "glTexCoordP3ui":        ("packed-type", "_glsTexCoord4f"),
    "glTexCoordP3uiv":       ("packed-type", "_glsTexCoord4f"),
    "glTexCoordP4ui":        ("packed-type", "_glsTexCoord4f"),
    "glTexCoordP4uiv":       ("packed-type", "_glsTexCoord4f"),
    "glVertexAttribP1ui":    ("packed-type", "_glsVertexAttrib4f"),
    "glVertexAttribP1uiv":   ("packed-type", "_glsVertexAttrib4f"),
    "glVertexAttribP2ui":    ("packed-type", "_glsVertexAttrib4f"),
    "glVertexAttribP2uiv":   ("packed-type", "_glsVertexAttrib4f"),
    "glVertexAttribP3ui":    ("packed-type", "_glsVertexAttrib4f"),
    "glVertexAttribP3uiv":   ("packed-type", "_glsVertexAttrib4f"),
    "glVertexAttribP4ui":    ("packed-type", "_glsVertexAttrib4f"),
    "glVertexAttribP4uiv":   ("packed-type", "_glsVertexAttrib4f"),
    "glVertexP2ui":          ("packed-type", "_glsVertex4f"),
    "glVertexP2uiv":         ("packed-type", "_glsVertex4f"),
    "glVertexP3ui":          ("packed-type", "_glsVertex4f"),
    "glVertexP3uiv":         ("packed-type", "_glsVertex4f"),
    "glVertexP4ui":          ("packed-type", "_glsVertex4f"),
    "glVertexP4uiv":         ("packed-type", "_glsVertex4f"),
    # ----- integer-variant (30) -----
    "glGetSamplerParameterIiv":  ("integer-variant", None),
    "glGetSamplerParameterIuiv": ("integer-variant", None),
    "glGetTexParameterIiv":      ("integer-variant", "_glsGetTexParameteriv"),
    "glGetTexParameterIuiv":     ("integer-variant", "_glsGetTexParameteriv"),
    "glGetVertexAttribIiv":      ("integer-variant", None),
    "glGetVertexAttribIuiv":     ("integer-variant", None),
    "glSamplerParameterIiv":     ("integer-variant", "_glsSamplerParameteri"),
    "glSamplerParameterIuiv":    ("integer-variant", "_glsSamplerParameteri"),
    "glTexParameterIiv":         ("integer-variant", "_glsTexParameteri"),
    "glTexParameterIuiv":        ("integer-variant", "_glsTexParameteri"),
    "glVertexAttribI1i":         ("integer-variant", "_glsVertexAttrib4f"),
    "glVertexAttribI1iv":        ("integer-variant", "_glsVertexAttrib4f"),
    "glVertexAttribI1ui":        ("integer-variant", "_glsVertexAttrib4f"),
    "glVertexAttribI1uiv":       ("integer-variant", "_glsVertexAttrib4f"),
    "glVertexAttribI2i":         ("integer-variant", "_glsVertexAttrib4f"),
    "glVertexAttribI2iv":        ("integer-variant", "_glsVertexAttrib4f"),
    "glVertexAttribI2ui":        ("integer-variant", "_glsVertexAttrib4f"),
    "glVertexAttribI2uiv":       ("integer-variant", "_glsVertexAttrib4f"),
    "glVertexAttribI3i":         ("integer-variant", "_glsVertexAttrib4f"),
    "glVertexAttribI3iv":        ("integer-variant", "_glsVertexAttrib4f"),
    "glVertexAttribI3ui":        ("integer-variant", "_glsVertexAttrib4f"),
    "glVertexAttribI3uiv":       ("integer-variant", "_glsVertexAttrib4f"),
    "glVertexAttribI4bv":        ("integer-variant", "_glsVertexAttrib4f"),
    "glVertexAttribI4i":         ("integer-variant", "_glsVertexAttrib4f"),
    "glVertexAttribI4iv":        ("integer-variant", "_glsVertexAttrib4f"),
    "glVertexAttribI4sv":        ("integer-variant", "_glsVertexAttrib4f"),
    "glVertexAttribI4ubv":       ("integer-variant", "_glsVertexAttrib4f"),
    "glVertexAttribI4ui":        ("integer-variant", "_glsVertexAttrib4f"),
    "glVertexAttribI4uiv":       ("integer-variant", "_glsVertexAttrib4f"),
    "glVertexAttribI4usv":       ("integer-variant", "_glsVertexAttrib4f"),
    # ----- gl14-variant (28) -----
    "glSecondaryColor3b":   ("gl14-variant", "_glsSecondaryColor3f"),
    "glSecondaryColor3bv":  ("gl14-variant", "_glsSecondaryColor3f"),
    "glSecondaryColor3d":   ("gl14-variant", "_glsSecondaryColor3f"),
    "glSecondaryColor3dv":  ("gl14-variant", "_glsSecondaryColor3f"),
    "glSecondaryColor3i":   ("gl14-variant", "_glsSecondaryColor3f"),
    "glSecondaryColor3iv":  ("gl14-variant", "_glsSecondaryColor3f"),
    "glSecondaryColor3s":   ("gl14-variant", "_glsSecondaryColor3f"),
    "glSecondaryColor3sv":  ("gl14-variant", "_glsSecondaryColor3f"),
    "glSecondaryColor3ui":  ("gl14-variant", "_glsSecondaryColor3f"),
    "glSecondaryColor3uiv": ("gl14-variant", "_glsSecondaryColor3f"),
    "glSecondaryColor3us":  ("gl14-variant", "_glsSecondaryColor3f"),
    "glSecondaryColor3usv": ("gl14-variant", "_glsSecondaryColor3f"),
    "glWindowPos2d":        ("gl14-variant", "_glsWindowPos3f"),
    "glWindowPos2dv":       ("gl14-variant", "_glsWindowPos3f"),
    "glWindowPos2f":        ("gl14-variant", "_glsWindowPos3f"),
    "glWindowPos2fv":       ("gl14-variant", "_glsWindowPos3f"),
    "glWindowPos2i":        ("gl14-variant", "_glsWindowPos3f"),
    "glWindowPos2iv":       ("gl14-variant", "_glsWindowPos3f"),
    "glWindowPos2s":        ("gl14-variant", "_glsWindowPos3f"),
    "glWindowPos2sv":       ("gl14-variant", "_glsWindowPos3f"),
    "glWindowPos3d":        ("gl14-variant", "_glsWindowPos3f"),
    "glWindowPos3dv":       ("gl14-variant", "_glsWindowPos3f"),
    "glWindowPos3f":        ("gl14-variant", "_glsWindowPos3f"),
    "glWindowPos3fv":       ("gl14-variant", "_glsWindowPos3f"),
    "glWindowPos3i":        ("gl14-variant", "_glsWindowPos3f"),
    "glWindowPos3iv":       ("gl14-variant", "_glsWindowPos3f"),
    "glWindowPos3s":        ("gl14-variant", "_glsWindowPos3f"),
    "glWindowPos3sv":       ("gl14-variant", "_glsWindowPos3f"),
    # ----- get-gap (20) -----
    "glGetAttachedShaders":        ("get-gap", None),
    "glGetBooleani_v":             ("get-gap", "_glsGetBooleanv"),
    "glGetDoublei_v":              ("get-gap", "_glsGetFloatv"),
    "glGetFloati_v":               ("get-gap", "_glsGetFloatv"),
    "glGetFramebufferParameteriv": ("get-gap", "_glsGetIntegerv"),
    "glGetInteger64i_v":           ("get-gap", "_glsGetIntegerv"),
    "glGetIntegeri_v":             ("get-gap", "_glsGetIntegerv"),
    "glGetSamplerParameterfv":     ("get-gap", None),
    "glGetSamplerParameteriv":     ("get-gap", None),
    "glGetShaderPrecisionFormat":  ("get-gap", None),
    "glGetShaderSource":           ("get-gap", None),
    "glGetUniformdv":              ("get-gap", None),
    "glGetUniformfv":              ("get-gap", None),
    "glGetUniformiv":              ("get-gap", None),
    "glGetUniformuiv":             ("get-gap", None),
    "glGetVertexAttribLdv":        ("get-gap", None),
    "glGetVertexAttribPointerv":   ("get-gap", None),
    "glGetVertexAttribdv":         ("get-gap", None),
    "glGetVertexAttribfv":         ("get-gap", None),
    "glGetVertexAttribiv":         ("get-gap", None),
    # ----- uniform-widen (20) -----
    "glUniform1ui":         ("uniform-widen", "_glsUniform1i"),
    "glUniform1uiv":        ("uniform-widen", "_glsUniform1iv"),
    "glUniform2ui":         ("uniform-widen", "_glsUniform2i"),
    "glUniform2uiv":        ("uniform-widen", "_glsUniform2iv"),
    "glUniform3ui":         ("uniform-widen", "_glsUniform3i"),
    "glUniform3uiv":        ("uniform-widen", "_glsUniform3iv"),
    "glUniform4ui":         ("uniform-widen", "_glsUniform4i"),
    "glUniform4uiv":        ("uniform-widen", "_glsUniform4iv"),
    "glUniformMatrix2x3dv": ("uniform-widen", "_glsUniform4fv"),
    "glUniformMatrix2x3fv": ("uniform-widen", "_glsUniform4fv"),
    "glUniformMatrix2x4dv": ("uniform-widen", "_glsUniform4fv"),
    "glUniformMatrix2x4fv": ("uniform-widen", "_glsUniform4fv"),
    "glUniformMatrix3x2dv": ("uniform-widen", "_glsUniform4fv"),
    "glUniformMatrix3x2fv": ("uniform-widen", "_glsUniform4fv"),
    "glUniformMatrix3x4dv": ("uniform-widen", "_glsUniform4fv"),
    "glUniformMatrix3x4fv": ("uniform-widen", "_glsUniform4fv"),
    "glUniformMatrix4x2dv": ("uniform-widen", "_glsUniform4fv"),
    "glUniformMatrix4x2fv": ("uniform-widen", "_glsUniform4fv"),
    "glUniformMatrix4x3dv": ("uniform-widen", "_glsUniform4fv"),
    "glUniformMatrix4x3fv": ("uniform-widen", "_glsUniform4fv"),
    # ----- robustness (19) -----
    "glGetnColorTable":         ("robustness", None),
    "glGetnCompressedTexImage": ("robustness", "_glsGetCompressedTexImage"),
    "glGetnConvolutionFilter":  ("robustness", None),
    "glGetnHistogram":          ("robustness", None),
    "glGetnMapdv":              ("robustness", "_glsGetMapfv"),
    "glGetnMapfv":              ("robustness", "_glsGetMapfv"),
    "glGetnMapiv":              ("robustness", "_glsGetMapiv"),
    "glGetnMinmax":             ("robustness", None),
    "glGetnPixelMapfv":         ("robustness", "_glsGetPixelMapfv"),
    "glGetnPixelMapuiv":        ("robustness", "_glsGetPixelMapuiv"),
    "glGetnPixelMapusv":        ("robustness", "_glsGetPixelMapusv"),
    "glGetnPolygonStipple":     ("robustness", "_glsGetPolygonStipple"),
    "glGetnSeparableFilter":    ("robustness", None),
    "glGetnTexImage":           ("robustness", "_glsGetTexImage"),
    "glGetnUniformdv":          ("robustness", None),
    "glGetnUniformfv":          ("robustness", None),
    "glGetnUniformiv":          ("robustness", None),
    "glGetnUniformuiv":         ("robustness", None),
    "glReadnPixels":            ("robustness", "_glsReadPixels"),
    # ----- indexed-state (13) -----
    "glBeginQueryIndexed":      ("indexed-state",
        "{ if (index != 0) return; _glsBeginQuery((unsigned int)target, (unsigned int)id); }"),
    "glBlendEquationSeparatei": ("indexed-state",
        "{ if (buf != 0) return; _glsBlendEquationSeparate((unsigned int)modeRGB, (unsigned int)modeAlpha); }"),
    "glBlendFuncSeparatei":     ("indexed-state",
        "{ if (buf != 0) return; _glsBlendFuncSeparate((unsigned int)srcRGB, (unsigned int)dstRGB, (unsigned int)srcAlpha, (unsigned int)dstAlpha); }"),
    "glDepthRangeArrayv":       ("indexed-state",
        "{ if (first != 0 || count < 1 || !v) return; _glsDepthRange((double)v[0], (double)v[1]); }"),
    "glDepthRangeIndexed":      ("indexed-state",
        "{ if (index != 0) return; _glsDepthRange((double)n, (double)f); }"),
    "glEndQueryIndexed":        ("indexed-state",
        "{ if (index != 0) return; _glsEndQuery((unsigned int)target); }"),
    "glGetQueryIndexediv":      ("indexed-state",
        "{ if (index != 0) return; _glsGetQueryiv((unsigned int)target, (unsigned int)pname, (int *)params); }"),
    "glScissorArrayv":          ("indexed-state",
        "{ if (first != 0 || count < 1 || !v) return; _glsScissor((int)v[0], (int)v[1], (int)v[2], (int)v[3]); }"),
    "glScissorIndexed":         ("indexed-state",
        "{ if (index != 0) return; _glsScissor((int)left, (int)bottom, (int)width, (int)height); }"),
    "glScissorIndexedv":        ("indexed-state",
        "{ if (index != 0 || !v) return; _glsScissor((int)v[0], (int)v[1], (int)v[2], (int)v[3]); }"),
    "glViewportArrayv":         ("indexed-state",
        "{ if (first != 0 || count < 1 || !v) return; _glsViewport((int)v[0], (int)v[1], (int)v[2], (int)v[3]); }"),
    "glViewportIndexedf":       ("indexed-state",
        "{ if (index != 0) return; _glsViewport((int)x, (int)y, (int)w, (int)h); }"),
    "glViewportIndexedfv":      ("indexed-state",
        "{ if (index != 0 || !v) return; _glsViewport((int)v[0], (int)v[1], (int)v[2], (int)v[3]); }"),
    # ----- fp64-demote (11) -----
    "glUniform1d":        ("fp64-demote", "_glsUniform1f"),
    "glUniform1dv":       ("fp64-demote", "_glsUniform1fv"),
    "glUniform2d":        ("fp64-demote", "_glsUniform2f"),
    "glUniform2dv":       ("fp64-demote", "_glsUniform2fv"),
    "glUniform3d":        ("fp64-demote", "_glsUniform3f"),
    "glUniform3dv":       ("fp64-demote", "_glsUniform3fv"),
    "glUniform4d":        ("fp64-demote", "_glsUniform4f"),
    "glUniform4dv":       ("fp64-demote", "_glsUniform4fv"),
    "glUniformMatrix2dv": ("fp64-demote", "_glsUniformMatrix2fv"),
    "glUniformMatrix3dv": ("fp64-demote", "_glsUniformMatrix3fv"),
    "glUniformMatrix4dv": ("fp64-demote", "_glsUniformMatrix4fv"),
    # ----- is-misc (7) -----
    "glClampColor":  ("is-misc", None),
    "glClearDepthf": ("is-misc", "_glsClearDepth"),
    "glDepthRangef": ("is-misc", "_glsDepthRange"),
    "glIsEnabledi":  ("is-misc", "_glsIsEnabled"),
    "glIsQuery":     ("is-misc", None),
    "glIsSampler":   ("is-misc", None),
    "glIsSync":      ("is-misc", None),
    # ----- multi-bind (5) -----
    "glBindBuffersBase":   ("multi-bind",
        "{ GLsizei _genI; for (_genI = 0; _genI < count; _genI++) _glsBindBufferBase((unsigned int)target, (unsigned int)((GLsizei)first + _genI), (unsigned int)(buffers ? buffers[_genI] : 0)); }"),
    "glBindBuffersRange":  ("multi-bind",
        "{ GLsizei _genI; for (_genI = 0; _genI < count; _genI++) _glsBindBufferRange((unsigned int)target, (unsigned int)((GLsizei)first + _genI), (unsigned int)(buffers ? buffers[_genI] : 0), (ptrdiff_t)(offsets ? offsets[_genI] : 0), (ptrdiff_t)(sizes ? sizes[_genI] : 0)); }"),
    "glBindImageTextures": ("multi-bind",
        "{ GLsizei _genI; for (_genI = 0; _genI < count; _genI++) _glsBindImageTexture((unsigned int)((GLsizei)first + _genI), (unsigned int)(textures ? textures[_genI] : 0), 0, 0, 0, (unsigned int)GL_READ_WRITE, (unsigned int)GL_RGBA8); }"),
    "glBindSamplers":      ("multi-bind",
        "{ GLsizei _genI; for (_genI = 0; _genI < count; _genI++) _glsBindSampler((unsigned int)((GLsizei)first + _genI), (unsigned int)(samplers ? samplers[_genI] : 0)); }"),
    "glBindTextures":      ("multi-bind",
        "{ GLsizei _genI; for (_genI = 0; _genI < count; _genI++) _genBindTextureUnit((GLuint)((GLsizei)first + _genI), (GLuint)(textures ? textures[_genI] : 0)); }"),
    # ----- tf-bookkeeping (6) -----
    "glBindTransformFeedback":    ("tf-bookkeeping", None),
    "glDeleteTransformFeedbacks": ("tf-bookkeeping", None),
    "glGenTransformFeedbacks":    ("tf-bookkeeping", None),
    "glIsTransformFeedback":      ("tf-bookkeeping", None),
    "glPauseTransformFeedback":   ("tf-bookkeeping", None),
    "glResumeTransformFeedback":  ("tf-bookkeeping", None),
    # ----- direct-forward (7) -----
    "glFramebufferTextureLayer": ("direct-forward",
        "_glsFramebufferTexture((unsigned int)target, (unsigned int)attachment, (unsigned int)texture, (int)level)"),
    "glMemoryBarrierByRegion":   ("direct-forward",
        "_glsMemoryBarrier((unsigned int)barriers)"),
    "glPolygonOffsetClamp":      ("direct-forward",
        "_glsPolygonOffset((float)factor, (float)units)"),
    "glTexBufferRange":          ("direct-forward",
        "_glsTexBufferRange((unsigned int)target, (unsigned int)internalformat, (unsigned int)buffer, (ptrdiff_t)offset, (ptrdiff_t)size)"),
    "glTexStorage1D":            ("direct-forward",
        "_glsTexStorage2D((unsigned int)target, (int)levels, (unsigned int)internalformat, (int)width, 1)"),
    "glTexStorage2DMultisample": ("direct-forward",
        "_glsTexStorage2D((unsigned int)target, 1, (unsigned int)internalformat, (int)width, (int)height)"),
    "glTexStorage3DMultisample": ("direct-forward",
        "_glsTexStorage3D((unsigned int)target, 1, (unsigned int)internalformat, (int)width, (int)height, (int)depth)"),
    # ----- noop-legal (11) -----
    "glDebugMessageInsert":       ("noop-legal", None),
    "glInvalidateBufferData":     ("noop-legal", None),
    "glInvalidateBufferSubData":  ("noop-legal", None),
    "glInvalidateFramebuffer":    ("noop-legal", None),
    "glInvalidateSubFramebuffer": ("noop-legal", None),
    "glInvalidateTexImage":       ("noop-legal", None),
    "glInvalidateTexSubImage":    ("noop-legal", None),
    "glObjectPtrLabel":           ("noop-legal", None),
    "glPopDebugGroup":            ("noop-legal", None),
    "glPushDebugGroup":           ("noop-legal", None),
    "glReleaseShaderCompiler":    ("noop-legal", None),
    # ----- ceiling-noop (81) -----
    "glActiveShaderProgram":                         ("ceiling-noop", None),
    "glBindFragDataLocation":                        ("ceiling-noop", None),
    "glBindFragDataLocationIndexed":                 ("ceiling-noop", None),
    "glBindProgramPipeline":                         ("ceiling-noop", None),
    "glBindVertexBuffer":                            ("ceiling-noop", None),
    "glBindVertexBuffers":                           ("ceiling-noop", None),
    "glBufferStorage":                               ("ceiling-noop", None),
    "glClearBufferData":                             ("ceiling-noop", None),
    "glClearBufferSubData":                          ("ceiling-noop", None),
    "glClearTexImage":                               ("ceiling-noop", None),
    "glClearTexSubImage":                            ("ceiling-noop", None),
    "glCopyImageSubData":                            ("ceiling-noop", None),
    "glCreateShaderProgramv":                        ("ceiling-noop", None),
    "glDeleteProgramPipelines":                      ("ceiling-noop", None),
    "glDispatchComputeIndirect":                     ("ceiling-noop", None),
    "glDrawArraysIndirect":                          ("ceiling-noop", None),
    "glDrawArraysInstancedBaseInstance":             ("ceiling-noop", None),
    "glDrawElementsBaseVertex":                      ("ceiling-noop", None),
    "glDrawElementsIndirect":                        ("ceiling-noop", None),
    "glDrawElementsInstancedBaseInstance":           ("ceiling-noop", None),
    "glDrawElementsInstancedBaseVertex":             ("ceiling-noop", None),
    "glDrawElementsInstancedBaseVertexBaseInstance": ("ceiling-noop", None),
    "glDrawRangeElementsBaseVertex":                 ("ceiling-noop", None),
    "glDrawTransformFeedback":                       ("ceiling-noop", None),
    "glDrawTransformFeedbackInstanced":              ("ceiling-noop", None),
    "glDrawTransformFeedbackStream":                 ("ceiling-noop", None),
    "glDrawTransformFeedbackStreamInstanced":        ("ceiling-noop", None),
    "glFramebufferParameteri":                       ("ceiling-noop", None),
    "glGenProgramPipelines":                         ("ceiling-noop", None),
    "glGetActiveAtomicCounterBufferiv":              ("ceiling-noop", None),
    "glGetActiveSubroutineName":                     ("ceiling-noop", None),
    "glGetActiveSubroutineUniformName":              ("ceiling-noop", None),
    "glGetActiveSubroutineUniformiv":                ("ceiling-noop", None),
    "glGetActiveUniformBlockName":                   ("ceiling-noop", None),
    "glGetActiveUniformBlockiv":                     ("ceiling-noop", None),
    "glGetActiveUniformName":                        ("ceiling-noop", None),
    "glGetActiveUniformsiv":                         ("ceiling-noop", None),
    "glGetDebugMessageLog":                          ("ceiling-noop", None),
    "glGetFragDataIndex":                            ("ceiling-noop", None),
    "glGetFragDataLocation":                         ("ceiling-noop", None),
    "glGetGraphicsResetStatus":                      ("ceiling-noop", None),
    "glGetInternalformati64v":                       ("ceiling-noop", None),
    "glGetInternalformativ":                         ("ceiling-noop", None),
    "glGetObjectLabel":                              ("ceiling-noop", None),
    "glGetObjectPtrLabel":                           ("ceiling-noop", None),
    "glGetProgramBinary":                            ("ceiling-noop", None),
    "glGetProgramInterfaceiv":                       ("ceiling-noop", None),
    "glGetProgramPipelineInfoLog":                   ("ceiling-noop", None),
    "glGetProgramPipelineiv":                        ("ceiling-noop", None),
    "glGetProgramResourceIndex":                     ("ceiling-noop", None),
    "glGetProgramResourceLocation":                  ("ceiling-noop", None),
    "glGetProgramResourceLocationIndex":             ("ceiling-noop", None),
    "glGetProgramResourceName":                      ("ceiling-noop", None),
    "glGetProgramResourceiv":                        ("ceiling-noop", None),
    "glGetProgramStageiv":                           ("ceiling-noop", None),
    "glGetSubroutineIndex":                          ("ceiling-noop", None),
    "glGetSubroutineUniformLocation":                ("ceiling-noop", None),
    "glGetSynciv":                                   ("ceiling-noop", None),
    "glGetUniformIndices":                           ("ceiling-noop", None),
    "glGetUniformSubroutineuiv":                     ("ceiling-noop", None),
    "glIsProgramPipeline":                           ("ceiling-noop", None),
    "glMultiDrawArraysIndirect":                     ("ceiling-noop", None),
    "glMultiDrawArraysIndirectCount":                ("ceiling-noop", None),
    "glMultiDrawElementsBaseVertex":                 ("ceiling-noop", None),
    "glMultiDrawElementsIndirect":                   ("ceiling-noop", None),
    "glMultiDrawElementsIndirectCount":              ("ceiling-noop", None),
    "glPatchParameterfv":                            ("ceiling-noop", None),
    "glProgramBinary":                               ("ceiling-noop", None),
    "glProgramParameteri":                           ("ceiling-noop", None),
    "glShaderBinary":                                ("ceiling-noop", None),
    "glShaderStorageBlockBinding":                   ("ceiling-noop", None),
    "glSpecializeShader":                            ("ceiling-noop", None),
    "glUniformSubroutinesuiv":                       ("ceiling-noop", None),
    "glUseProgramStages":                            ("ceiling-noop", None),
    "glValidateProgramPipeline":                     ("ceiling-noop", None),
    "glVertexAttribBinding":                         ("ceiling-noop", None),
    "glVertexAttribFormat":                          ("ceiling-noop", None),
    "glVertexAttribIFormat":                         ("ceiling-noop", None),
    "glVertexAttribLFormat":                         ("ceiling-noop", None),
    "glVertexAttribLPointer":                        ("ceiling-noop", None),
    "glVertexBindingDivisor":                        ("ceiling-noop", None),
}
